name: Check

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '**'

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: 14

      - name: Install npm deps
        if: steps.cache-npm.outputs.cache-hit != 'true'
        run: npm ci

      - name: Build typescript libraries
        run: npm run build

      - name: Install @nrwl/cli globally
        run: npm i -g @nrwl/cli

      - name: Build the project
        run: nx build       

      - name: Create preview
        uses: ethersphere/swarm-actions/pr-preview@v0
        with:
          bee-url: https://unlimited.gateway.ethswarm.org
          dir: ./dist/apps/remix-ide/
          error-document: index.html
          headers: "${{ secrets.GATEWAY_AUTHORIZATION_HEADER }}"
